### ISSUE TITLE
Add some kind of paths config to prevent very long relative paths

### ISSUE THREAD

**Issue by isochronous** [timrwood/includer#10]
It would, I think, be very useful if includer were to add support for mapping certain paths to identifiers that could then be used in include statements.  (I should probably mention that I'll be using includer via the `gulp-includer` plugin, if that makes a difference.)

For example, we've got an unusual project where many scripts in our project's "Scripts" folder are concatenated with includer, but saved to a long folder name outside of the "Scripts" directory.  Here's a very basic diagram of just a small portion of these files/folders:

```
-- Packages
  |
  |- Src
    |
    |- Ally
    |
    |- Ally Audit
        |
        |- Reporting
        |
        |- Reports
            |
            |- AuditRecap
              |
              |= auditRecapReport.combined.js
-- Scripts
  |
  |- Src
    |
    |- Ally
      |
      |- Ad Hoc
        |
        |- Config
          |
          |= adHoc.combined.js
```

So we might have several files in the same folder where `adHoc.combined.js` is located, and those files are included by `auditRecapReport.combined.js`.  That means that we have MANY relative include paths like this:
`include('../../../../../../Scripts/src/Ally/Ad Hoc/Config/somefile.js');`, which is not only a problem because of its length and visual parsing complexity, but also makes the project structure very brittle.

I have two suggestions: one would be to treat paths with leading slashes as being relative to the project root (i.e. where the root `node_modules` folder is located, or better yet, using some kind of `baseUrl` option that simply defaults to the directory containing the root `node_modules` folder):

``` js
include('/Scripts/src/Ally/Ad Hoc/config/somefile.js');
```

That's the simple option.  The more flexible option would be to have some kind of paths config, similar to what's supported by requireJS, where you could pass an object like this:

``` js
paths: {
    "scriptsrc" : "Scripts/src", // or "/Scripts/src",
    "packagesrc": "Packages/src" // or "/Packages/src"
    // etc
}
```

as one of the options to includer, and then use some kind of token replacement in the include paths:

``` js
include('{{scriptsrc}}/Ally/Ad Hoc/config/somefile.js');
include('{{packagesrc}}/Ally/Ally Audit/Reporting/Reports/allReports.js');
```

Obviously you'd run the token replacement logic before globbing the path, and you'd have to determine an acceptable syntax to use that wouldn't unintentionally screw with globs, but I don't think that this would actually be too difficult to accomplish.

**Comment by isochronous** [comment]
Here's a completely untested first pass at implementing something like this:

``` js
File.prototype.replaceTokens = function (filepath) {
    var base = process.cwd,
        rgx = /{{([\w\d]+)}}/,
        paths, match, key, mapping, basedMapping, fragment, mapped;
    // exit early if there's nothing to do
    if (!this.opts.paths) {
        return filepath;
    } else {
        paths = this.opts.paths;
    }
    // check for tokens in the filepath
    match = filepath.match(rgx);
    if (match) {
        // key will be at first index of match (token without the surrounding {{ }} )
        key = match[1];
        // look for a corresponding key in the paths config
        if (mapping = paths[key]) {
            // now, to be safe, instead of just doing a string replacement, we should try to resolve
            // all the bits of the path we're manipulating.  start with resolving the base with the mapping
            baseMapping = path.resolve(base, mapping);
            // now remove the token from the filepath, and resolve what's left with the baseMapping
            fragment = filepath.replace(match[0], '');
            mapped = path.resolve(baseMapping, fragment);
            return mapped;
        }
    }
    return filepath;
};
```

**Comment by isochronous** [comment]
Hrmmm... the basepath functionality seem to already be there due to the `this.filepath = path.resolve(filepath);`, but when I try using an absolute path like `include('/src/whatever.js');` the include doesn't work.  I'll debug a little bit more on my end and let you know what I find - it may be a platform-specific problem like the last one was.

**Comment by isochronous** [comment]
Well, for now, I think that the full `paths` config idea would still be nice, but I'd still need to spend more time than I currently have figuring out how best to implement it.  I did, however, figure out how to implement the `baseUrl` implementation, where baseUrl defaults to `process.cwd()` but can be overridden in the options.  I'll be submitting a pull request once I add some tests for this use case.

``` js
function splitToGlobOrTextNode(node, text) {
    var basePath = path.dirname(node.filepath);
    var matchPath = match(text);

    if (matchPath) {
        if (!path.extname(matchPath)) {
            matchPath += '.js';
        }
        // If attempting to use an absolute path relative to the baseUrl, don't
        // process paths relative to the including file, process them relative to the
        // baseUrl instead.
        if (matchPath.charAt(0) === '/' || matchPath.charAt(0) === '\\') {
            basePath = node.file.opts.baseUrl || process.cwd();
            // On windows, at least, attempting to do a path.resolve of d:\some\dir and
            // /some/other/dir still results d:\some\other\dir. Adding a self-reference
            // to the matchPath resolves this problem.
            matchPath = '.' + matchPath;
        }
        return new GlobNode(path.resolve(basePath, matchPath), node.file);
    }

    return new TextNode(node.filepath, text);
}
```

**Comment by isochronous** [comment]
Now that I've had some time to think about it, I have a slightly different idea, and I'd like to get your opinion on it.

In some frameworks, the `~` character is used to specify the project root, or what I've thus far been referring to as the baseUrl.  Because some people may already be using includer in a way that assumes `/` or `\` characters _should_ map to the drive root, I'm a bit hesitant to change that functionality so drastically.  So instead I'm thinking about adopting the `~` convention for includes, so that any include path starting with a `~` will be considered relative to `opts.baseUrl || process.cwd()`, and paths beginning with slashes will work as they always have.

I'm also still thinking about the path tokens, and decided to take an approach similar to that of requireJS, where the first path segment (e.x. `foo` in `foo/bar`) would be automatically checked for a path mapping, and if no mapping is found, would simply use the regular ol' `foo/bar` path.

Just to be clear, here's an example of what I'm talking about (again, in the context of the gulp-includer plugin):

``` js
// In the gulpfile
/* snip */
.pipe(includer({
    paths: {
        "baz": "~/foo/bar/baz"
    }
}))
/* snip */

// and now in someFile.js
include('baz/someFileInFooBarBaz.js');

// transformed to
include('<project root>/foo/bar/baz/someFileInFooBarBaz.js');
```

If there were also a `baz` folder in the same folder as `someFile.js`, then you could still easily reference it with `include('./baz/someOtherFile.js');`

Thoughts?

**Comment by timrwood** [comment]
There is definitely a use case for path aliases, but I think it should be very clear when a path alias is being used.

I really don't want to have `include('bar/baz.js')` lookup `bar` from the aliases, as it would make adding aliases difficult later on in a project, as you would have to scour all your files to make sure the new alias didn't break local path references on anything else.

I think this could be pretty easily solved with replacement tokens as you suggested initially.

We could use `@alias` as a replacement token. This reads aloud nicely. Include some-file at the baz alias root.

``` js
include('@baz/some-file.js');
```

While this is unlikely to have file path collisions, it is possible that someone names their folder `/@baz`, in which case they would still need to add `./@baz` to reference the folder literally.

Another option would be to use `:` as a replacement token.

``` js
include(':baz/some-file.js');
```

This has the benefit of being an illegal path character on both windows and unix systems, so there shouldn't be any file path collisions.

_side note:_ it would also be cool if includer supported remote urls as well.

``` js
include('http://code.jquery.com/jquery-2.1.1.min.js');
```

Now about the `cwd` alias. Because all of the paths passed to `include(path)` are relative, I think all aliases would need to be resolved before they are replaced. There are some weird cases where just replacing the aliases would make the paths really weird.

``` js
includer({
    paths: {
        "baz": ".."
    }
})

// in foo/file.js
include(':baz/other.js'); // foo/../other.js     = other.js

// in foo/bar/file.js
include(':baz/other.js'); // foo/bar/../other.js = foo/other.js
```

So I think all aliases should be relative to the current working directory.

``` js
includer({
    paths: {
        "baz": "path/to/baz"
    }
})

// in foo/file.js
include(':baz/other.js'); // path/to/baz/other.js

// in foo/bar/file.js
include(':baz/other.js'); // path/to/baz/other.js
```

As far as the specific alias for the cwd, `~` is a shorthand for the home directory (eg `/Users/timrwood`) on unix systems. I think there might be some confusion with unix users, so maybe we could just add a built in alias `:cwd`.

``` js
include(':cwd/source/js/some-file.js');
```

**Comment by isochronous** [comment]
Okay - I've actually got all of my previous proposal working, including unit tests.. kinda.  I'm running into problems with line endings in the unit tests, as the line endings on your system are different than mine, so when includer joins the files together on my system, the actual result has different line endings than the expected files generated on your system. I could fix this by re-saving all of the expected files, I suppose, but then that would screw up the unit tests on your system.  I attempted to resolve this by using `os.EOL` as the default separator, but again, because my os.EOL and your os.EOL are different, the actual and expected results differ.

It shouldn't be too difficult to switch my code over to using the `@alias` format, though I do think that the situation you're worried about is easily solved by always using relative paths in the format `./dirname` instead of just `dirname`.  Personally, I also don't really see a problem with allowing users to change what the base is from `cwd()` to whatever they want.  Again, I already have this working perfectly on my system.  The use case that you're worried about (`{baz: '..'}`)... well,  that's close to something I've needed to do in the past, when we've had the "Scripts" folder as the default baseUrl, but we needed an alias to a directory outside of the "Scripts" folder tree, so it was more like `{ css: '~/../Content/css' }`.  Notice that all of the path mappings I proposed start with the "base path reference" character, just to be clear that the mappings are always going to be relative to the process root.

The main reason in both of these cases is that requireJS and several other tools I've used use the exact pattern I proposed, and requireJS alone is used on a very wide scale.

Anyway, I'm checking in what I currently have, and will submit a pull request that you can just leave open, and we can hammer out the details in that thread.

**Comment by isochronous** [comment]
Arg, my git repo just blew up and I had to recreate a bunch of stuff from scratch... so annoying.  Will get that pull request to you once I make sure unit tests are still passing.

**Comment by isochronous** [comment]
Okay, cool - still seeing the line ending problem with the unit tests, but at least they're working as intended.  Pull request incoming.

**Comment by timrwood** [comment]
Closing in favor of #11 and #12.
